# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msg_item.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'msg_item.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msg_common_pb2 as msg__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emsg_item.proto\x12\x08msg_item\x1a\x10msg_common.proto\"L\n\x0c\x43\x32S_USE_ITEM\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x10\n\x08item_num\x18\x02 \x01(\x03\x12\x0b\n\x03\x65xt\x18\x03 \x01(\x05\x12\x0c\n\x04\x65xt2\x18\x04 \x01(\x05\"\x0e\n\x0cS2C_USE_ITEM\"P\n\x15\x43\x32S_USE_ITEM_MULTIPLE\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12&\n\x05items\x18\x02 \x03(\x0b\x32\x17.msg_common.common_item\"\x17\n\x15S2C_USE_ITEM_MULTIPLE\"O\n\x19S2C_USE_ITEM_MULTI_RESULT\x12\x0b\n\x03tid\x18\x01 \x01(\x05\x12%\n\x04\x61\x64\x64s\x18\x02 \x03(\x0b\x32\x17.msg_common.common_item\"6\n\x11\x43\x32S_COMPOUND_ITEM\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x10\n\x08item_num\x18\x02 \x01(\x03\"\x13\n\x11S2C_COMPOUND_ITEM\"G\n\x08\x62\x61\x63kpack\x12\x13\n\x0b\x62\x61\x63kpack_id\x18\x01 \x01(\x05\x12&\n\x05items\x18\x02 \x03(\x0b\x32\x17.msg_common.common_item\"#\n\x0c\x43\x32S_BACKPACK\x12\x13\n\x0b\x62\x61\x63kpack_id\x18\x01 \x03(\x05\"5\n\x0cS2C_BACKPACK\x12%\n\tbackpacks\x18\x01 \x03(\x0b\x32\x12.msg_item.backpack\"<\n\x13S2C_BACKPACK_UPDATE\x12%\n\tbackpacks\x18\x01 \x03(\x0b\x32\x12.msg_item.backpack\"A\n\x11S2C_SYNC_ITEM_NUM\x12,\n\x04item\x18\x01 \x03(\x0b\x32\x1e.msg_common.common_item_change\"6\n\x13S2C_ITEM_NOT_ENOUGH\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0brequire_num\x18\x02 \x01(\x03\x42\x0cZ\n./../../pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_item_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n./../../pb'
  _globals['_C2S_USE_ITEM']._serialized_start=46
  _globals['_C2S_USE_ITEM']._serialized_end=122
  _globals['_S2C_USE_ITEM']._serialized_start=124
  _globals['_S2C_USE_ITEM']._serialized_end=138
  _globals['_C2S_USE_ITEM_MULTIPLE']._serialized_start=140
  _globals['_C2S_USE_ITEM_MULTIPLE']._serialized_end=220
  _globals['_S2C_USE_ITEM_MULTIPLE']._serialized_start=222
  _globals['_S2C_USE_ITEM_MULTIPLE']._serialized_end=245
  _globals['_S2C_USE_ITEM_MULTI_RESULT']._serialized_start=247
  _globals['_S2C_USE_ITEM_MULTI_RESULT']._serialized_end=326
  _globals['_C2S_COMPOUND_ITEM']._serialized_start=328
  _globals['_C2S_COMPOUND_ITEM']._serialized_end=382
  _globals['_S2C_COMPOUND_ITEM']._serialized_start=384
  _globals['_S2C_COMPOUND_ITEM']._serialized_end=403
  _globals['_BACKPACK']._serialized_start=405
  _globals['_BACKPACK']._serialized_end=476
  _globals['_C2S_BACKPACK']._serialized_start=478
  _globals['_C2S_BACKPACK']._serialized_end=513
  _globals['_S2C_BACKPACK']._serialized_start=515
  _globals['_S2C_BACKPACK']._serialized_end=568
  _globals['_S2C_BACKPACK_UPDATE']._serialized_start=570
  _globals['_S2C_BACKPACK_UPDATE']._serialized_end=630
  _globals['_S2C_SYNC_ITEM_NUM']._serialized_start=632
  _globals['_S2C_SYNC_ITEM_NUM']._serialized_end=697
  _globals['_S2C_ITEM_NOT_ENOUGH']._serialized_start=699
  _globals['_S2C_ITEM_NOT_ENOUGH']._serialized_end=753
# @@protoc_insertion_point(module_scope)
