syntax = "proto3";
package msg_medal_boss;

message medal_boss_hero_item {
  int64 rid = 1;
  string roleName = 2;
  int64 hid = 3;
  int64 remainTimes = 4;
  int64 totalTimes = 5;
  int64 sword = 6;
  int64 starLv = 7;
  int64 lv = 8;
}

message medal_boss_notice_item {
  // boxer: unknown field number
  int64 bossId = 2;
  int64 boxConfId = 3;
  int64 boxId = 4;
  int64 taked = 5;
}

message C2S_MEDAL_BOSS_INFO {}

message S2C_MEDAL_BOSS_INFO {
  int64 status = 1;
  int64 sessionId = 2;
  int64 bossId = 3;
  int64 bossHp = 4;
  int64 guildHelpRemainCount = 5;
  // guildHeroes: unknown field number
  // mineHeroes: unknown field number
  // notices: unknown field number
}

message C2S_MEDAL_BOSS_BATTLE {
  int64 heroRid = 1;
  int64 heroId = 2;
}

message S2C_MEDAL_BOSS_BATTLE {
  int64 bossId = 1;
  int64 bossHp = 2;
  // guildHeroes: unknown field number
  // mineHeroes: unknown field number
}

message C2S_MEDAL_BOSS_OPEN {
  int64 boxId = 1;
}

message S2C_MEDAL_BOSS_OPEN {
  int64 boxId = 1;
  int64 taked = 2;
}

message C2S_MEDAL_BOSS_NEW_NOTICE {}

message S2C_MEDAL_BOSS_NEW_NOTICE {
  // notice: unknown field number
}

message C2S_MEDAL_BOSS_NEW_LUCK {}

message S2C_MEDAL_BOSS_NEW_LUCK {
  // lucker: unknown field number
  // boxer: unknown field number
  int64 itemId = 3;
}
