syntax = "proto3";
package msg_banquet;

message banquet_info {
  int64 id = 1;
  int64 cid = 2;
  // holder: unknown field number
  // participants: unknown field number
  int64 participantsCount = 5;
  int64 holdTime = 6;
  int64 remainTime = 7;
  int64 myRole = 8;
  int64 reward = 9;
  // legalGifts: unknown field number
  int64 extraId = 31;
  int64 giftExp = 25;
  int64 canTaked = 26;
}

message banquet_hold_count {
  int64 type = 1;
  int64 count = 2;
  int64 extraId = 3;
  int64 startTime = 4;
}

message ROLE_BANQUET_INFO {
  int64 id = 1;
  int64 cid = 2;
  int64 count = 3;
  int64 remainTime = 4;
}

message C2S_ROLE_BANQUET {}

message S2C_ROLE_BANQUET {
  // normalBanquet: unknown field number
  // grandBanquet: unknown field number
  // banquetHoldCount: unknown field number
  int64 identityAdd = 6;
  int64 heroAdd = 7;
  int64 warshipAdd = 8;
}

message banquet_simple_info {
  int64 id = 1;
  int64 cid = 2;
  // holder: unknown field number
  int64 count = 4;
  int64 holdTime = 5;
  int64 remainTime = 6;
  int64 myRole = 7;
  int64 totalEarn = 8;
}

message C2S_GLOBAL_BANQUET {
  int64 tid = 1;
  int64 isAdvanced = 2;
}

message S2C_GLOBAL_BANQUET {
  // infos: unknown field number
}

message C2S_BANQUET_INFO {
  int64 id = 1;
}

message S2C_BANQUET_INFO {
  // info: unknown field number
}

message C2S_HOLD_BANQUET {
  int64 cId = 1;
  int64 extraId = 2;
}

message S2C_HOLD_BANQUET {
  // infos: unknown field number
}

message C2S_JOIN_BANQUET {
  int64 banquetId = 1;
  int64 giftLevel = 2;
}

message S2C_JOIN_BANQUET {
  int64 score = 1;
  int64 gold = 2;
  int64 diamond = 3;
}

message C2S_CHANGE_BANQUET_LEVEL {
  int64 banquetId = 1;
  // legalGifts: unknown field number
}

message S2C_CHANGE_BANQUET_LEVEL {
  int64 banquetId = 1;
  // legalGifts: unknown field number
}

message C2S_CLAIM_BANQUET_GIFT {
  int64 banquetId = 1;
}

message S2C_CLAIM_BANQUET_GIFT {
  int64 banquetId = 1;
  int64 canTaked = 2;
}

message banquet_hold_simple_record {
  int64 cid = 1;
  int64 endTime = 2;
  int64 count = 3;
  int64 score = 4;
  string holdName = 5;
  int64 id = 6;
}

message C2S_BANQUET_HOLD_RECORD {
  int64 min = 1;
  int64 max = 2;
}

message S2C_BANQUET_HOLD_RECORD {
  // records: unknown field number
}

message banquet_exchange_info {
  // rid: unknown field number
  int64 giftLevel = 2;
  int64 giftScore = 3;
  int64 joinMyCount = 4;
  int64 myJoinCount = 5;
}

message C2S_BANQUET_RECORD {
  int64 id = 1;
}

message S2C_BANQUET_RECORD {
  // records: unknown field number
}

message grade_banquet_simple_record {
  int64 cid = 1;
  // hold: unknown field number
  int64 holdTime = 3;
  int64 joinNum = 4;
}

message C2S_GRAND_BANQUET_RECORD {
  int64 min = 1;
  int64 max = 2;
}

message S2C_GRAND_BANQUET_RECORD {
  // records: unknown field number
}

message C2S_GRAND_JOINERS {
  int64 bid = 1;
}

message S2C_GRAND_JOINERS {
  int64 bid = 1;
  // joinInfo: unknown field number
  int64 gold = 3;
  int64 score = 4;
  int64 diamond = 5;
}

message banquet_join_info {
  string roleName = 1;
  int64 score = 2;
  int64 rid = 3;
}

message S2C_SYNC_BANQUET_INFO {
  int64 id = 1;
  int64 gold = 2;
  int64 score = 3;
  int64 diamond = 4;
  // joinInfo: unknown field number
}

message S2C_SYNC_BANQUET_JOIN {
  // info: unknown field number
}

message S2C_SYNC_BANQUET_END {
  int64 id = 1;
}

message S2C_SYNC_NEW_BANQUET {
  int64 id = 1;
  int64 cid = 2;
  // holder: unknown field number
  // holderTitles: unknown field number
}
