syntax = "proto3";
package msg_travel;

message TRAVEL_RESULT {
  int64 round = 1;
  // items: unknown field number
  // event: unknown field number
}

message travel_event {
  int64 eventId = 1;
  int64 eventDataType = 2;
  string eventData = 3;
  int64 eventValue = 4;
}

message WARSHIP_PROGRESS {
  int64 warshipId = 1;
  int64 progress = 2;
}

message C2S_TRAVEL_INFO {}

message S2C_TRAVEL_INFO {
  // eventId: unknown field number
  // warshipProgress: unknown field number
}

message C2S_TRAVEL {
  int64 travelTime = 1;
  int64 source = 2;
}

message S2C_TRAVEL {
  // travelResult: unknown field number
  int64 source = 2;
  int64 code = 3;
}

message C2S_TRAVEL_EVENT_DEAL_WITH {
  int64 eventId = 1;
  int64 option = 2;
  int64 extend = 3;
  int64 source = 4;
}

message S2C_TRAVEL_EVENT_DEAL_WITH {
  // items: unknown field number
  int64 eventType = 2;
  int64 success = 3;
  // heroInfo: unknown field number
  // event: unknown field number
  int64 source = 6;
  int64 code = 7;
}
