syntax = "proto3";
package msg_common;
option go_package = "./../../pb";

// 公共消息体

// 公用进度条
message common_lv_process {
    int32 lv  = 1;  // 当前等级
    int64 exp = 2;  // 当前经验
}

// 公用进度
message common_process {
    int32 achievement = 1;  // 类型
    int32 process     = 2;  // 进度
}

// 公用数量物品
message common_item {
    int32 id    = 1;
    int64 count = 2;  // 数量
}

message common_items {
    repeated common_item items = 1;
}

// 多语言参数
message CHARACTERS_PARAM {
    int32 param_type   = 1;  // 参数类型
    string param_value = 2;  // 参数值
}

// 公用过期物品
message common_item_expire {
    int32 id        = 1;  // player_frame.xlsx id
    int64 expire_at = 2;  // 过期时间戳 1000==1sec -1 不过期
}
// 通用道具数目改变
message common_item_change {
    int32 id            = 1;  // 道具配置id
    string change_count = 2;  // 道具改变量
    string count        = 3;  // 道具最终量
}
// 展示道具
message common_item_show {
    int32 id               = 1;  // 道具配置id
    int64 count            = 2;  // 获得值
    int32 item_common_type = 3;  // 通用类型
}

// NOTICE: 不能使用共用回调，协议必须成对出现！
// NOTICE: 不能使用共用回调，协议必须成对出现！
// NOTICE: 不能使用共用回调，协议必须成对出现！
// 公用回调成功
// message common_success{
//     uint32 code = 1;//协议code
// }

message common_lv {
    int32 id = 1;  // 配表ID
    int32 lv = 2;  // 等级
}

message common_lv_type {
    int32 id  = 1;  // 配表ID
    int32 tid = 2;  // 类型ID
    int32 lv  = 3;  // 等级
}

message common_item_value {
    int32 id    = 1;  // 配表ID
    int32 value = 2;
}

// 通用获得道具奖励
message common_item_record {
    string name                = 1;  // 玩家名字
    repeated common_item items = 2;  // 获得道具奖励
}

// 四维
message attribute {
    attribute_item zhan_shu     = 1;  // 战术
    attribute_item jing_ji      = 2;  // 经济
    attribute_item tong_shuai   = 3;  // 统帅
    attribute_item bai_ren_zhan = 4;  // 白刃战
    uint32 total                = 5;
}

message attribute_item {
    int32 value                       = 1;  // 总值
    repeated attribute_detail details = 2;  // 详细
}

message attribute_detail {
    int32 cid   = 1;  // 类型
    int32 value = 2;  // 加成值
}

message role_simple_info {
    int32 rid         = 1;   // 人物id
    string name       = 2;   // 名称
    int32 hand        = 3;   // 头像
    int32 hand_frame  = 4;   // 头像框
    int32 level       = 5;   // 等级
    int32 vip_level   = 6;   // vip等级
    int32 guild_id    = 7;   // 公会id
    int32 server_id   = 8;   // 服务器id
    int32 image_id    = 10;  // 玩家立绘
    string guild_name = 11;  // 公会名字
    int32 role_type   = 12;  // 1真实玩家 2机器人
    int32 title_id    = 13;  // 称号id
    int32 skin_id     = 14;  // 皮肤id
    string lang       = 15;  // 语言
    int64 hero_combat = 16;  // 英雄战力
}

message RANKING_INFO_ROLE {
    int32 rid        = 1;  // 玩家rid
    int32 serv_id    = 2;  // 区服id
    int32 lv         = 3;  // 玩家等级
    int32 vip_lv     = 4;  // vip等级
    int32 head       = 5;  // 玩家头像
    int32 head_frame = 6;  // 头像框
    string name      = 7;  // 玩家名称
    int32 title_id   = 8;  // 称号
    int32 skin_id    = 9;  // TODO create_role 的 image 临时解决方案，等皮肤做好再优化，皮肤要抽独立的配表
}

message RANKING_INFO_GUILD {
    int32 head     = 1;  // 头像
    string name    = 2;  // 名称
    int32 lv       = 3;  // 等级
    int32 guild_id = 4;  // 师团id
}

message RANKING_INFO_SERVER {
    int32 id    = 1;  // 区服id
    string name = 2;  // 区服名字
}

// // 新皮肤，统一弹窗协议
// // message C2S_SKIN_NEW{
// // }
// message S2C_SKIN_NEW{
//     int32 mid=1;// 1 主角皮肤 2英雄皮肤
//     int32 oid=2;// 目标对象，主角皮肤 0，英雄皮肤是英雄的配表ID
//     common_lv skin=3;
// }

// message rank_cfg_info {
//     int32 startRank              = 1;  // 开始排名
//     int32 endRank                = 2;  // 结束排名
//     repeated common_item rewards = 3;  // 排行榜奖励
// }

message ai_activity_rank_info {
    int64 v                           = 1;  // 排行榜分数
    msg_common.RANKING_INFO_ROLE role = 2;  // 玩家信息
}

message ai_activity_rank_server_info {
    int64 v                               = 1;  // 排行榜分数
    msg_common.RANKING_INFO_SERVER server = 2;  // 区服信息
}

message ai_activity_rank_guild_info {
    int64 v                                   = 1;  // 排行榜分数
    msg_common.RANKING_INFO_GUILD guild       = 2;  // 公会信息
    msg_common.RANKING_INFO_ROLE role = 3;  // 公会会长信息
}

// 奖励记录
message reward_record {
    string name    = 1;  // 玩家名字
    int32 item_id  = 2;  // 道具id
    int32 item_num = 3;  // 道具数量
}

message common_kv {
    int32 key   = 1;  // 键
    int64 value = 2;  // 值
}

message common_kvs {
    repeated common_kv list = 1;  // 列表
}

message guild_simple_info {
    int32 guild_id    = 1;  // 公会id
    int32 guild_lv    = 2;  // 公会等级
    string guild_name = 3;  // 公会名字
    int32 guild_icon  = 4;  // 公会头像
    int32 master_rid  = 5;  // 公会会长id
    int32 server_id   = 6;  // 服务器id
}

message common_repeated_int32 {
    repeated int32 list = 1;
}

message common_map_int32_repeated_int32 {
    map<int32,common_repeated_int32> list = 1;
}

