syntax = "proto3";
package msg_player_medal;

message medal_skill {
  int64 id = 1;
  // current: unknown field number
  // replace: unknown field number
  int64 refreshCost = 4;
}

message medal {
  int64 id = 1;
  int64 mid = 2;
  int64 lv = 3;
  int64 upgradeLv = 4;
  int64 attribute = 5;
  // skills: unknown field number
  int64 bindHeroId = 7;
  // haloes: unknown field number
  int64 todayReplaceTimes = 9;
  int64 nextReplaceConsume = 10;
}

message C2S_MEDAL_LIST {}

message S2C_MEDAL_LIST {
  // medals: unknown field number
  int64 lvMax = 2;
  int64 upgradeLvMax = 3;
}

message C2S_MEDAL_ILLUSTRATION {}

message S2C_MEDAL_ILLUSTRATION {
  // medalCids: unknown field number
}

message C2S_MEDAL_LV_UP {
  int64 id = 1;
  int64 times = 2;
}

message S2C_MEDAL_LV_UP {
  int64 id = 1;
  int64 lv = 2;
  int64 attribute = 3;
}

message C2S_MEDAL_SKILL_REFRESH {
  int64 id = 1;
  int64 sid = 2;
  int64 tid = 3;
}

message S2C_MEDAL_SKILL_REFRESH {
  int64 id = 1;
  // skill: unknown field number
}

message C2S_MEDAL_SKILL_REPLACE {
  int64 id = 1;
  int64 sid = 2;
}

message S2C_MEDAL_SKILL_REPLACE {
  int64 id = 1;
  // skill: unknown field number
}

message C2S_MEDAL_UPGRADE {
  int64 id = 1;
}

message S2C_MEDAL_UPGRADE {
  int64 id = 1;
  int64 upgradeLv = 2;
  // skills: unknown field number
}

message C2S_MEDAL_SALE {
  // id: unknown field number
}

message S2C_MEDAL_SALE {
  // medals: unknown field number
}

message C2S_MEDAL_NEW {}

message S2C_MEDAL_NEW {
  // medal: unknown field number
}

message S2C_MEDAL_CHANGE_NOTICE {
  int64 id = 1;
  // haloes: unknown field number
}

message S2C_MEDAL_LV_MAX_CHANGE {
  int64 lvMax = 1;
  int64 upgradeLvMax = 2;
}

message C2S_MEDAL_REPLACE_TIMES {}

message S2C_MEDAL_REPLACE_TIMES {
  int64 mid = 1;
  int64 todayReplaceTimes = 2;
  int64 nextReplaceConsume = 3;
}
