syntax = "proto3";
package msg_chat_new;

message C2S_CHAT_INFO {}

message S2C_CHAT_INFO {
  string token = 1;
  string groupServer = 2;
  string groupServerGuild = 3;
  string groupWorld = 4;
  string groupWorldBanquet = 5;
  string groupTravel = 6;
  string groupServerGvg = 7;
}

message C2S_CHAT_HISTORY {
  string channel = 1;
}

message S2C_CHAT_HISTORY {
  string channel = 1;
  // datas: unknown field number
}

message C2S_CHAT_SEND {
  string channel = 1;
  string data = 2;
}

message S2C_CHAT_SEND {}

message S2C_CHAT_SYNC {
  string channel = 1;
  // datas: unknown field number
}
