# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msg_recharge.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'msg_recharge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12msg_recharge.proto\x12\x0cmsg_recharge\"5\n\rRECHARGE_INFO\x12\x12\n\nrechargeId\x18\x01 \x01(\x03\x12\x10\n\x08isDouble\x18\x02 \x01(\x03\"/\n\nVIP_REWARD\x12\x0e\n\x06itemId\x18\x01 \x01(\x03\x12\x11\n\titemCount\x18\x02 \x01(\x03\"\x13\n\x11\x43\x32S_RECHARGE_INFO\"2\n\x11S2C_RECHARGE_INFO\x12\x0e\n\x06vipExp\x18\x02 \x01(\x03\x12\r\n\x05vipLv\x18\x03 \x01(\x03\"\'\n\x13\x43\x32S_CARD_GET_REWARD\x12\x10\n\x08\x63\x61rdType\x18\x01 \x01(\x03\"\x15\n\x13S2C_CARD_GET_REWARD\")\n\x18\x43\x32S_GET_VIP_LEVEL_REWARD\x12\r\n\x05level\x18\x01 \x01(\x03\"\x1a\n\x18S2C_GET_VIP_LEVEL_REWARD\"h\n\x19\x43\x32S_RECHARGE_CREATE_ORDER\x12\x12\n\nrechargeId\x18\x01 \x01(\x03\x12\x14\n\x0crechargeName\x18\x02 \x01(\t\x12\x0f\n\x07\x65xtends\x18\x03 \x01(\t\x12\x10\n\x08isDaibi2\x18\x04 \x01(\x03\"`\n\x19S2C_RECHARGE_CREATE_ORDER\x12\x12\n\nrechargeId\x18\x01 \x01(\x03\x12\x0f\n\x07orderNo\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\x12\x0f\n\x07\x65xtends\x18\x04 \x01(\t\"H\n\x13S2C_RECHARGE_DELIVE\x12\x12\n\nrechargeId\x18\x01 \x01(\x03\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x03\x12\x0f\n\x07\x65xtends\x18\x03 \x01(\t\"3\n\x14recharge_config_item\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\t\"\x1a\n\x18\x43\x32S_RECHARGE_CONFIG_LIST\"\x1a\n\x18S2C_RECHARGE_CONFIG_LIST\"\x1c\n\x1a\x43\x32S_RECHARGE_DAIBI2_WALLET\"\x1c\n\x1aS2C_RECHARGE_DAIBI2_WALLETb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_recharge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECHARGE_INFO']._serialized_start=36
  _globals['_RECHARGE_INFO']._serialized_end=89
  _globals['_VIP_REWARD']._serialized_start=91
  _globals['_VIP_REWARD']._serialized_end=138
  _globals['_C2S_RECHARGE_INFO']._serialized_start=140
  _globals['_C2S_RECHARGE_INFO']._serialized_end=159
  _globals['_S2C_RECHARGE_INFO']._serialized_start=161
  _globals['_S2C_RECHARGE_INFO']._serialized_end=211
  _globals['_C2S_CARD_GET_REWARD']._serialized_start=213
  _globals['_C2S_CARD_GET_REWARD']._serialized_end=252
  _globals['_S2C_CARD_GET_REWARD']._serialized_start=254
  _globals['_S2C_CARD_GET_REWARD']._serialized_end=275
  _globals['_C2S_GET_VIP_LEVEL_REWARD']._serialized_start=277
  _globals['_C2S_GET_VIP_LEVEL_REWARD']._serialized_end=318
  _globals['_S2C_GET_VIP_LEVEL_REWARD']._serialized_start=320
  _globals['_S2C_GET_VIP_LEVEL_REWARD']._serialized_end=346
  _globals['_C2S_RECHARGE_CREATE_ORDER']._serialized_start=348
  _globals['_C2S_RECHARGE_CREATE_ORDER']._serialized_end=452
  _globals['_S2C_RECHARGE_CREATE_ORDER']._serialized_start=454
  _globals['_S2C_RECHARGE_CREATE_ORDER']._serialized_end=550
  _globals['_S2C_RECHARGE_DELIVE']._serialized_start=552
  _globals['_S2C_RECHARGE_DELIVE']._serialized_end=624
  _globals['_RECHARGE_CONFIG_ITEM']._serialized_start=626
  _globals['_RECHARGE_CONFIG_ITEM']._serialized_end=677
  _globals['_C2S_RECHARGE_CONFIG_LIST']._serialized_start=679
  _globals['_C2S_RECHARGE_CONFIG_LIST']._serialized_end=705
  _globals['_S2C_RECHARGE_CONFIG_LIST']._serialized_start=707
  _globals['_S2C_RECHARGE_CONFIG_LIST']._serialized_end=733
  _globals['_C2S_RECHARGE_DAIBI2_WALLET']._serialized_start=735
  _globals['_C2S_RECHARGE_DAIBI2_WALLET']._serialized_end=763
  _globals['_S2C_RECHARGE_DAIBI2_WALLET']._serialized_start=765
  _globals['_S2C_RECHARGE_DAIBI2_WALLET']._serialized_end=793
# @@protoc_insertion_point(module_scope)
