syntax = "proto3";
package msg_activity_core;

message activity_item {
  // id: unknown field number
  // status: unknown field number
  int64 expireTs = 3;
  int64 atid = 4;
  string activityContent = 5;
  string rewardGroup = 6;
  string taskGroup = 7;
  int64 readyStartAt = 8;
  int64 readyEndAt = 9;
  int64 startAt = 10;
  int64 endAt = 11;
  int64 rewardStartAt = 12;
  int64 rewardEndAt = 13;
}

message C2S_ACTIVITY_LIST {}

message S2C_ACTIVITY_LIST {
  // activities: unknown field number
}

message S2C_ACTIVITY_UPDATE {
  // activity: unknown field number
}

message C2S_ACTIVITY_MULTI_LIST {
  int64 id = 1;
}

message S2C_ACTIVITY_MULTI_LIST {
  // activities: unknown field number
}

message C2S_ACTIVITY_JOIN {
  // id: unknown field number
}

message S2C_ACTIVITY_JOIN {}
