syntax = "proto3";
package msg_reputation;

message REPUTATION_ROLE_INFO {
  int64 rid = 1;
  string roleName = 2;
  int64 vipLv = 3;
  int64 imageId = 4;
  int64 servId = 5;
  int64 ts = 6;
  int64 index = 7;
  int64 lv = 8;
  int64 headId = 9;
  int64 headFrameId = 10;
}

message REPUTATION_INFO {
  int64 reputationType = 1;
  int64 achievementProgress = 2;
  // getProgress: unknown field number
  int64 likeNum = 4;
}

message C2S_REPUTATION_INFO {}

message S2C_REPUTATION_INFO {
  // reputationInfo: unknown field number
  // buffId: unknown field number
  int64 worshipNum = 3;
}

message C2S_REPUTATION_ACHIEVEMENT_GET {
  int64 reputationType = 1;
  int64 progress = 2;
}

message S2C_REPUTATION_ACHIEVEMENT_GET {
  int64 reputationType = 1;
  int64 achievementProgress = 2;
  // getProgress: unknown field number
}

message C2S_REPUTATION_BOOK_INFO {
  int64 reputationType = 1;
}

message S2C_REPUTATION_BOOK_INFO {
  // roleInfo: unknown field number
  int64 maxId = 2;
}

message C2S_REPUTATION_WORSHIP {
  int64 source = 1;
}

message S2C_REPUTATION_WORSHIP {
  int64 buffId = 1;
  // roleInfo: unknown field number
  // items: unknown field number
  int64 reputationType = 4;
  int64 source = 5;
  int64 code = 6;
}

message C2S_REPUTATION_LIKE {
  int64 reputationType = 1;
  int64 source = 2;
}

message S2C_REPUTATION_LIKE {
  int64 reputationType = 1;
  int64 source = 2;
  // items: unknown field number
  int64 code = 4;
}
