syntax = "proto3";
package msg_share_gift;

message SHARE_GIFT_MEMBER {
  int64 rid = 1;
  string name = 2;
  int64 hand = 3;
  int64 handFrame = 4;
  int64 level = 5;
  int64 vipLevel = 6;
  int64 guildId = 7;
  int64 serverId = 8;
  int64 imageId = 9;
  int64 isThank = 10;
}

message C2S_SHARE_GIFT_INFO {
  string packetId = 1;
  int64 channelId = 2;
}

message S2C_SHARE_GIFT_INFO {
  string packetId = 1;
  int64 cfgId = 2;
  int64 rewardTimes = 3;
  // shareMember: unknown field number
  // rewardMembers: unknown field number
}

message C2S_SHARE_GIFT_THANK {
  string packetId = 1;
}

message S2C_SHARE_GIFT_THANK {}
