syntax = "proto3";
package msg_gvg;

message STRONG_HOLD {
  int64 id = 1;
  int64 level = 2;
  int64 status = 3;
  int64 fleetPos = 4;
  int64 endTs = 5;
  // roleInfo: unknown field number
}

message HERO_ITEM {
  int64 hid = 1;
  int64 hp = 2;
}

message WARSHIP_ITEM {
  int64 wid = 1;
  int64 atk = 2;
  int64 def = 3;
  // heros: unknown field number
}

message FLEET_ITEM {
  int64 wid = 1;
  // heroids: unknown field number
}

message FLEET_INFO {
  int64 fleetPos = 1;
  // fleetItem: unknown field number
}

message GVG_BATTLE_REPORT {
  // roleInfo: unknown field number
  int64 isSuccess = 2;
  // curFleets: unknown field number
  // tarFleets: unknown field number
  int64 strongholdId = 5;
  int64 atkRid = 6;
}

message C2S_GVG_INFO {}

message S2C_GVG_INFO {
  // stronghold: unknown field number
}

message C2S_STRONG_HOLD_INFO {
  int64 id = 1;
}

message S2C_STRONG_HOLD_INFO {
  // tarFleets: unknown field number
  // roleInfo: unknown field number
}

message C2S_GVG_BUILD_FLEET {
  // fleet: unknown field number
}

message S2C_GVG_BUILD_FLEET {
  // fleets: unknown field number
}

message C2S_GVG_FLEET_LIST {}

message S2C_GVG_FLEET_LIST {
  // fleets: unknown field number
}

message C2S_GVG_FIGHT {
  int64 fleetPos = 1;
  int64 strongholdId = 2;
  int64 occupy = 3;
}

message S2C_GVG_FIGHT {
  int64 fleetPos = 1;
  // battleReport: unknown field number
  int64 isCamp = 3;
  int64 occupy = 4;
}

message C2S_GVG_FIGHT_REPORT {}

message S2C_GVG_FIGHT_REPORT {
  // battleReport: unknown field number
}

message C2S_GVG_IS_OPEN {}

message S2C_GVG_IS_OPEN {
  int64 isOpen = 1;
  int64 endTs = 2;
  int64 modeType = 3;
  int64 isCross = 4;
}
