syntax = "proto3";
package msg_global;

message global_item {
  int64 id = 1;
  string cid = 2;
  string v = 3;
}

message C2S_GLOBAL_HV_LIST {}

message S2C_GLOBAL_HV_LIST {
  // items: unknown field number
}

message S2C_GLOBAL_HV_UPDATE {
  // item: unknown field number
}

message MQ_MSG {
  int64 id = 1;
  // msgType: unknown field number
  int64 createdAt = 3;
  string data = 4;
}

message S2C_MQ_LIST {
  // msgs: unknown field number
}

message C2S_MQ_CONFIRM {
  int64 id = 1;
}

message S2C_MQ_CONFIRM {}

message FUNC_OPEN_TIME_DATA {
  // openTimeType: unknown field number
  int64 startTime = 2;
  int64 endTime = 3;
}

message C2S_FUNC_OPEN_TIME_LIST {}

message S2C_FUNC_OPEN_TIME_LIST {
  // list: unknown field number
}
