syntax = "proto3";
package msg_ba_134;

message BA134_PANEL_ITEM {
  int64 slot = 1;
  int64 rewardId = 2;
  int64 rewardCount = 3;
}

message BA134_PANEL {
  int64 panelId = 1;
  // items: unknown field number
}

message BA134_LOG_ITEM {
  string name = 1;
  int64 rewardId = 2;
  int64 rewardCount = 3;
}

message BA134_LOG {
  int64 panelId = 1;
  // items: unknown field number
}

message C2S_BA134_DASHBOARD {}

message S2C_BA134_DASHBOARD {
  // panels: unknown field number
  // logs: unknown field number
}

message C2S_BA134_OPEN {
  int64 panelId = 1;
  int64 slot = 2;
}

message S2C_BA134_OPEN {
  int64 panelId = 1;
  int64 slot = 2;
  int64 rewardId = 3;
  int64 rewardCount = 4;
  // items: unknown field number
  int64 autoRefresh = 6;
}

message C2S_BA134_REFRESH {
  int64 panelId = 1;
}

message S2C_BA134_REFRESH {
  int64 panelId = 1;
  // items: unknown field number
}
