syntax = "proto3";
package msg_player_role;

message C2S_PLAYER_ROLE_INFO {}

message S2C_PLAYER_ROLE_INFO {
  string name = 1;
  int64 id = 2;
  int64 lv = 3;
  int64 vipLv = 4;
  // frameActived: unknown field number
  // frameOwned: unknown field number
  int64 iconActived = 7;
  // iconOwned: unknown field number
  // skinActived: unknown field number
  // skinOwned: unknown field number
  // titleActived: unknown field number
  // titleOwned: unknown field number
  int64 initId = 13;
  int64 guildId = 14;
  // halos: unknown field number
  int64 days = 17;
  string currency = 18;
  int64 isDefaultName = 19;
  int64 showMainSkinId = 20;
  int64 createdTs = 21;
}

message S2C_PLAYER_ROLE_CREATE_DAYS {
  int64 days = 1;
}

message S2C_PLAYER_ROLE_HALO {
  // halos: unknown field number
}

message C2S_PLAYER_ROLE_LV_UP {}

message S2C_PLAYER_ROLE_LV_UP {
  int64 lv = 1;
}

message C2S_PLAYER_ROLE_CHANGE_NAME {
  string name = 1;
}

message S2C_PLAYER_ROLE_CHANGE_NAME {
  string name = 1;
}

message C2S_PLAYER_ROLE_CHANGE_SKIN {
  int64 id = 1;
}

message S2C_PLAYER_ROLE_CHANGE_SKIN {
  // skinActived: unknown field number
}

message S2C_PLAYER_SKIN_NEW {
  // skin: unknown field number
}

message C2S_PLAYER_ROLE_UNLOCK_SKIN {
  int64 id = 1;
}

message S2C_PLAYER_ROLE_UNLOCK_SKIN {}

message C2S_PLAYER_ROLE_UPGRADE_SKIN {
  int64 id = 1;
}

message S2C_PLAYER_ROLE_UPGRADE_SKIN {
  // skinActived: unknown field number
  // skinOwned: unknown field number
}

message C2S_PLAYER_ROLE_TILE {}

message S2C_PLAYER_ROLE_TILE {
  // titleActived: unknown field number
  // titleOwned: unknown field number
}

message C2S_PLAYER_ROLE_CHANGE_TILE {
  int64 id = 1;
}

message S2C_PLAYER_ROLE_CHANGE_TITLE {
  // titleActived: unknown field number
}

message C2S_PLAYER_ROLE_CHANGE_ICON {
  int64 id = 1;
}

message S2C_PLAYER_ROLE_CHANGE_ICON {
  int64 iconActived = 1;
}

message C2S_PLAYER_ROLE_CHANGE_FRAME {
  int64 id = 1;
}

message S2C_PLAYER_ROLE_CHANGE_FRAME {
  // frameActived: unknown field number
}

message C2S_PLAYER_ROLE_TAKE_DAILY_GIFT {
  int64 source = 1;
}

message S2C_PLAYER_ROLE_TAKE_DAILY_GIFT {
  int64 source = 1;
  // items: unknown field number
  int64 code = 3;
}

message S2C_PLAYER_SHOW_NOTICE {
  int64 id = 1;
  string params = 2;
}

message C2S_PLAYER_ROLE_COUNT_LIST {}

message S2C_PLAYER_ROLE_COUNT_LIST {
  // countMap: unknown field number
}

message C2S_PLAYER_OTHER_ROLE_INFO {
  int64 rid = 1;
}

message S2C_PLAYER_OTHER_ROLE_INFO {
  // role: unknown field number
  int64 likeCount = 2;
  int64 liked = 3;
}

message C2S_PLAYER_OTHER_ROLE_LIKE {
  int64 rid = 1;
}

message S2C_PLAYER_OTHER_ROLE_LIKE {
  int64 rid = 1;
  int64 likeCount = 2;
}
