syntax = "proto3";
package msg_item;
option go_package = "./../../pb";

import "msg_common.proto";

// 使用道具 道具类型为2.1 无法通过这个接口使用
message C2S_USE_ITEM {
    int32 item_id  = 1;  // 物品配置Id
    int64 item_num = 2;  // 使用的数量
    int32 ext      = 3;  // 扩展 2.3 传入选择的道具 2.11 选择对应的伙伴 2.12-2.13 选择对应的战舰
    int32 ext2     = 4;
}
message S2C_USE_ITEM {
}

message C2S_USE_ITEM_MULTIPLE {
    int32 item_id                         = 1;  // 使用的物品id
    repeated msg_common.common_item items = 2;  // 指定兑换的数量
}
message S2C_USE_ITEM_MULTIPLE {
}

// 道具使用效果，服务器主动通知
// message C2S_USE_ITEM_MULTI_RESULT{
// }
message S2C_USE_ITEM_MULTI_RESULT {
    int32 tid                            = 1;  // 1:工厂招募工人 2:英雄战力增加 3:战舰攻击增加 4:战舰防御增加
    repeated msg_common.common_item adds = 2;
}

// 合成道具
message C2S_COMPOUND_ITEM {
    int32 item_id  = 1;  // 合成的物品配置Id
    int64 item_num = 2;  // 合成的数量
}
message S2C_COMPOUND_ITEM {
}

// -----------分背包-------------
message backpack {
    int32 backpack_id                     = 1;  // 背包ID
    repeated msg_common.common_item items = 2;
}

// 拉背包数据
message C2S_BACKPACK {
    repeated int32 backpack_id = 1;  // 背包ID
}
message S2C_BACKPACK {
    repeated backpack backpacks = 1;
}

// 服务器主动推送，把道具放入背包。
// message C2S_BACKPACK_UPDATE{
// }
message S2C_BACKPACK_UPDATE {
    repeated backpack backpacks = 1;
}

// 服务器主动推送，通用弹窗显示奖励
// message C2S_SYNC_ITEM_NUM{
// }
message S2C_SYNC_ITEM_NUM {
    repeated msg_common.common_item_change item = 1;
}

// 服务器主动推送，道具不足弹窗
// message C2S_ITEM_NOT_ENOUGH{
// }
message S2C_ITEM_NOT_ENOUGH {
    int32 id          = 1;
    int64 require_num = 2;  // 请求消耗的数量
}
// -----------分背包-------------