syntax = "proto3";
package msg_user_shop;
option go_package = "./../../pb";

import "msg_common.proto";

// ！！程序里不要用！！
// ！！仅查看！！
enum SHOP_ID {
    shop_id_keeper = 0;

    // 商店
    BANQUET     = 1;   // 宴会商店
    REPUTATION  = 2;   // 名人堂商店
    TOWER       = 3;   // 讨伐商店
    MEDAL_BOSS  = 4;   // 勋章模拟战商店
    PVP         = 5;   // PVP商店
    GOCHA       = 6;   // 幸运夺宝商店
    SHOP        = 7;   // 系统商店
    BATTLE_PASS = 9;   // BP商店
    GUILD       = 10;  // 师团商店

    // 礼包
    SHOP_PACKAGE = 502;  // 系统商店礼包【活动的礼包也会汇总 append 到这个商店里】
    ACTIVITY_104 = 501;  // 七日福利礼包
}

message shop_info {
    int32 conf_id      = 1;  // 配表id
    int32 remain_count = 2;  // 剩余可购买次数
    int32 buy_count    = 3;  // 已购买次数
    int64 start_time   = 4;  // 上架时间戳，毫秒
    int64 end_time     = 5;  // 下架时间戳，毫秒
    int64 show_time    = 6;  // 开始展示时间戳，毫秒
}

message C2S_SHOP_SYS {    // 系统商店专用
    int32 shop_type = 1;  // 商店类型
    int32 cfg_id = 2; //活动的配表id
}
message S2C_SHOP_SYS {
    repeated shop_info infos = 1;
    int64 expire_at          = 2;  // 活动最早结束日期【仅 502 会返回，默认 0】
}

message C2S_SHOP_SYS_BUY {
    int32 shop_id   = 1;  // 商店唯一ID
    int32 conf_id   = 2;  // 商品配表id
    int32 buy_count = 3;  // 商店购买数目
    int32 cfgId     = 4;  // 活动的配表id
    int32 source    = 5;  // assistant.xlsx id；玩家手动购买填 0
}
message S2C_SHOP_SYS_BUY {
    shop_info info                       = 1;  // 商店购买信息变化
    int32 source                         = 2;  // assistant.xlsx id；玩家手动购买填 0
    repeated msg_common.common_item items = 3;  // 本次获得道具
    int32 code                           = 4;  // 0成功 1失败（助手吞错时）
}