# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msg_user_shop.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'msg_user_shop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msg_common_pb2 as msg__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13msg_user_shop.proto\x12\rmsg_user_shop\x1a\x10msg_common.proto\"~\n\tshop_info\x12\x0f\n\x07\x63onf_id\x18\x01 \x01(\x05\x12\x14\n\x0cremain_count\x18\x02 \x01(\x05\x12\x11\n\tbuy_count\x18\x03 \x01(\x05\x12\x12\n\nstart_time\x18\x04 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\x03\x12\x11\n\tshow_time\x18\x06 \x01(\x03\"1\n\x0c\x43\x32S_SHOP_SYS\x12\x11\n\tshop_type\x18\x01 \x01(\x05\x12\x0e\n\x06\x63\x66g_id\x18\x02 \x01(\x05\"J\n\x0cS2C_SHOP_SYS\x12\'\n\x05infos\x18\x01 \x03(\x0b\x32\x18.msg_user_shop.shop_info\x12\x11\n\texpire_at\x18\x02 \x01(\x03\"f\n\x10\x43\x32S_SHOP_SYS_BUY\x12\x0f\n\x07shop_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63onf_id\x18\x02 \x01(\x05\x12\x11\n\tbuy_count\x18\x03 \x01(\x05\x12\r\n\x05\x63\x66gId\x18\x04 \x01(\x05\x12\x0e\n\x06source\x18\x05 \x01(\x05\"\x80\x01\n\x10S2C_SHOP_SYS_BUY\x12&\n\x04info\x18\x01 \x01(\x0b\x32\x18.msg_user_shop.shop_info\x12\x0e\n\x06source\x18\x02 \x01(\x05\x12&\n\x05items\x18\x03 \x03(\x0b\x32\x17.msg_common.common_item\x12\x0c\n\x04\x63ode\x18\x04 \x01(\x05*\xb5\x01\n\x07SHOP_ID\x12\x12\n\x0eshop_id_keeper\x10\x00\x12\x0b\n\x07\x42\x41NQUET\x10\x01\x12\x0e\n\nREPUTATION\x10\x02\x12\t\n\x05TOWER\x10\x03\x12\x0e\n\nMEDAL_BOSS\x10\x04\x12\x07\n\x03PVP\x10\x05\x12\t\n\x05GOCHA\x10\x06\x12\x08\n\x04SHOP\x10\x07\x12\x0f\n\x0b\x42\x41TTLE_PASS\x10\t\x12\t\n\x05GUILD\x10\n\x12\x11\n\x0cSHOP_PACKAGE\x10\xf6\x03\x12\x11\n\x0c\x41\x43TIVITY_104\x10\xf5\x03\x42\x0cZ\n./../../pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_user_shop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n./../../pb'
  _globals['_SHOP_ID']._serialized_start=547
  _globals['_SHOP_ID']._serialized_end=728
  _globals['_SHOP_INFO']._serialized_start=56
  _globals['_SHOP_INFO']._serialized_end=182
  _globals['_C2S_SHOP_SYS']._serialized_start=184
  _globals['_C2S_SHOP_SYS']._serialized_end=233
  _globals['_S2C_SHOP_SYS']._serialized_start=235
  _globals['_S2C_SHOP_SYS']._serialized_end=309
  _globals['_C2S_SHOP_SYS_BUY']._serialized_start=311
  _globals['_C2S_SHOP_SYS_BUY']._serialized_end=413
  _globals['_S2C_SHOP_SYS_BUY']._serialized_start=416
  _globals['_S2C_SHOP_SYS_BUY']._serialized_end=544
# @@protoc_insertion_point(module_scope)
