syntax = "proto3";
package msg_warship;

message vice_ship {
  int64 id = 1;
  int64 atk = 3;
  int64 def = 4;
}

message vice_ship_skill {
  int64 id = 1;
  int64 lv = 2;
}

message WARSHIP_DATA {
  int64 warshipId = 1;
  int64 atk = 2;
  int64 def = 3;
  int64 warshipClass = 4;
  // flagshipIds: unknown field number
  int64 nextCruise2Cost = 6;
  int64 getTime = 7;
  int64 flightCount = 8;
  // factorySkill: unknown field number
  // supportSkill: unknown field number
  int64 supportSkillExp = 22;
  // supportSkillAdd: unknown field number
  // heroSkill: unknown field number
  int64 heroSkillExp = 16;
  // heroSkillAdd: unknown field number
  int64 wewLv = 25;
  // wewStatus: unknown field number
  // wewSkill: unknown field number
  // wewSkillAdd: unknown field number
  // vs: unknown field number
  // vsSkill: unknown field number
  // skinActived: unknown field number
  // skinOwned: unknown field number
}

message WARSHIP_SKILL {
  int64 skillId = 1;
  int64 skillLv = 2;
  int64 nextCost = 3;
  int64 nextAdd = 4;
  int64 skillType = 5;
  int64 add = 6;
  int64 lvUpTimes = 7;
  int64 skillLvMax = 8;
}

message SKILL_HERO {
  int64 heroId = 1;
  int64 addValue = 2;
}

message WARSHIP_CRUISE {
  int64 warshipId = 1;
  int64 num = 2;
}

message S2C_SYNC_WARSHIP_INFO {
  // warshipInfo: unknown field number
}

message S2C_WARSHIP_NEW {
  // warshipInfo: unknown field number
}

message S2C_SYNC_FACTORY_SKILL {
  // factorySkill: unknown field number
}

message C2S_WARSHIP_LIST {}

message S2C_WARSHIP_LIST {
  // warshipList: unknown field number
}

message C2S_WARSHIP_LVUP {
  int64 warshipId = 1;
}

message S2C_WARSHIP_LVUP {}

message C2S_WARSHIP_SKILL_LVUP {
  int64 warshipId = 1;
  int64 skillType = 2;
  int64 skillId = 3;
  int64 factorySkillType = 4;
}

message S2C_WARSHIP_SKILL_LVUP {
  // skillInfo: unknown field number
  int64 factoryResult = 2;
  // skillAdd: unknown field number
  int64 skillExp = 4;
}

message warship_flight_info {
  int64 flightIdx = 1;
  int64 flightCid = 2;
}

message C2S_WARSHIP_CRUISE {
  int64 cruiseType = 1;
  int64 cruiseNum = 2;
  int64 warshipId = 3;
  int64 source = 4;
}

message S2C_WARSHIP_CRUISE {
  // flights: unknown field number
  // wsrshipSruise: unknown field number
  int64 nextCruise2Cost = 3;
  int64 source = 4;
  // items: unknown field number
  int64 code = 6;
}

message WARSHIP_WEW_PARAM {
  int64 index = 1;
  // items: unknown field number
}

message C2S_WARSHIP_WEW {
  int64 warshipId = 1;
  // params: unknown field number
}

message S2C_WARSHIP_WEW {
  int64 warshipId = 1;
  int64 wewLv = 2;
  // wewStatus: unknown field number
  int64 wewLvChanged = 4;
}

message WARSHIP_CHANGE_SKIN {
  int64 warshipId = 1;
  int64 skinId = 2;
}

message S2C_WARSHIP_CHANGE_SKIN {
  int64 warshipId = 1;
  // skinActived: unknown field number
}
