syntax = "proto3";
package msg_flight_attendant;
option go_package = "./../../pb";

import "msg_common.proto";

// 未毕业乘务员信息
message FLIGHT_ATTENDANT_DATA {
    int32 idx                   = 1;  // 位置ID [1-5]
    int32 flight_attendant_id   = 2;  // 乘务员ID
    string name                 = 3;  // 名字
    int32 exp                   = 4;  // 经验
    int32 warship_id            = 5;  // 战舰ID
    int32 flight_attendant_type = 6;  // 乘务员类别
    int32 train_type            = 7;  // 培养方式

    int64 prod_total             = 8;   // 课税-总 [attributes]
    int64 prod_current           = 20;  // 课税-总-当前
    int64 prod_origin            = 9;   // 课税-基础属性 [NEW]
    int64 prod_quality           = 10;  // 课税-品质加成 [NEW]
    int64 prod_hero              = 11;  // 课税-伙伴天赋 [add_attributes]
    int64 prod_warship_class     = 12;  // 课税-战舰军衔 [add_warship]
    int64 prod_warship           = 13;  // 课税-战舰加成 [NEW]
    int64 prod_train_type        = 14;  // 课税-授学加成 [NEW]
    int64 prod_free_hero_precent = 21;  // 课税-费沙英雄-万分比
    int64 prod_free_hero         = 22;  // 课税-费沙英雄-数值

    int64 exp_total   = 15;  // 资历-总 [add_hero_exp]
    int64 exp_origin  = 16;  // 资历-基础 [NEW]
    int64 exp_quality = 17;  // 资历-品质 [NEW]
    int64 exp_hero    = 18;  // 资历-伙伴天赋 [NEW]
    int64 exp_warship = 19;  // 资历-战舰军衔 [add_quality] [从百分比改为万分比]
}

// 未毕业乘务员列表
message C2S_FLIGHT_ATTENDANT_LIST {}
message S2C_FLIGHT_ATTENDANT_LIST {
    repeated FLIGHT_ATTENDANT_DATA flight_attendants = 1;  // 未毕业乘务员
}

// 乘务员设置名字
message C2S_FLIGHT_ATTENDANT_SET_NAME {
    int32 idx                 = 1;  // 位置
    int32 flight_attendant_id = 2;  // 乘务员ID
    string name               = 3;  // 名字
    int32 train_type          = 4;  // 培养方式
}
message S2C_FLIGHT_ATTENDANT_SET_NAME {
    FLIGHT_ATTENDANT_DATA flight_attendant_data = 1;  // 乘务员数据
}

// 乘务员培养
message C2S_FLIGHT_ATTENDANT_TRAIN {
    int32 idx                 = 1;  // 位置
    int32 flight_attendant_id = 2;  // 乘务员ID
    int32 train_count         = 3;  // 培养次数 1 或 global 配表中的 63
    int32 source              = 4;  // assistant.xlsx id；玩家手动培养填 0
}
message S2C_FLIGHT_ATTENDANT_TRAIN {
    FLIGHT_ATTENDANT_DATA flight_attendant_data = 1;  // 乘务员数据
    int32 train_num                             = 2;  // 培养次数
    int32 train_add_exp                         = 3;  // 每次增加次数
    int32 source                                = 4;  // assistant.xlsx id；玩家手动培养填 0
    repeated msg_common.common_item items       = 5;  // 本次获得道具
    int32 code                                  = 6;  // 0成功 1失败（助手吞错时）
}

// 乘务员毕业
message C2S_FLIGHT_ATTENDANT_GRADUATION {
    int32 idx                 = 1;  // 位置
    int32 flight_attendant_id = 2;  // 乘务员ID
}
message S2C_FLIGHT_ATTENDANT_GRADUATION {
    msg_common.common_item items = 1;  // 毕业奖励
    int64 prod_total             = 2;  // 总课税，毕业时会变更一次
}