# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msg_sync.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'msg_sync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emsg_sync.proto\x12\x08msg_sync\"&\n\tS2C_ERROR\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x03\x12\x0b\n\x03pid\x18\x02 \x01(\x03\"\x0f\n\rS2C_CONNECTED\"\x19\n\tS2C_CLOSE\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x03\"\x10\n\x0e\x43\x32S_ENTER_GAME\"\x10\n\x0eS2C_ENTER_GAME\"%\n\x10S2C_RESET_NOTIFY\x12\x11\n\tresetType\x18\x01 \x01(\x03\")\n\x13S2C_RECHARGE_NOTIFY\x12\x12\n\nrechargeId\x18\x01 \x01(\x03\",\n\x0cHORN_CONTENT\x12\x0b\n\x03lan\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x1a\n\x18S2C_CONFIG_CHANGE_NOTIFYb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_S2C_ERROR']._serialized_start=28
  _globals['_S2C_ERROR']._serialized_end=66
  _globals['_S2C_CONNECTED']._serialized_start=68
  _globals['_S2C_CONNECTED']._serialized_end=83
  _globals['_S2C_CLOSE']._serialized_start=85
  _globals['_S2C_CLOSE']._serialized_end=110
  _globals['_C2S_ENTER_GAME']._serialized_start=112
  _globals['_C2S_ENTER_GAME']._serialized_end=128
  _globals['_S2C_ENTER_GAME']._serialized_start=130
  _globals['_S2C_ENTER_GAME']._serialized_end=146
  _globals['_S2C_RESET_NOTIFY']._serialized_start=148
  _globals['_S2C_RESET_NOTIFY']._serialized_end=185
  _globals['_S2C_RECHARGE_NOTIFY']._serialized_start=187
  _globals['_S2C_RECHARGE_NOTIFY']._serialized_end=228
  _globals['_HORN_CONTENT']._serialized_start=230
  _globals['_HORN_CONTENT']._serialized_end=274
  _globals['_S2C_CONFIG_CHANGE_NOTIFY']._serialized_start=276
  _globals['_S2C_CONFIG_CHANGE_NOTIFY']._serialized_end=302
# @@protoc_insertion_point(module_scope)
