# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msg_task.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'msg_task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msg_common_pb2 as msg__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emsg_task.proto\x12\x08msg_task\x1a\x10msg_common.proto\"]\n\tUSER_TASK\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x10\n\x08progress\x18\x02 \x01(\x03\x12\x11\n\tis_finish\x18\x03 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x03\x12\x0c\n\x04\x61rgs\x18\x05 \x03(\t\"J\n\x12S2C_SYNC_TASK_INFO\x12&\n\ttask_info\x18\x01 \x01(\x0b\x32\x13.msg_task.USER_TASK\x12\x0c\n\x04type\x18\x02 \x01(\x05\"\x1d\n\rC2S_TASK_LIST\x12\x0c\n\x04type\x18\x01 \x01(\x05\"p\n\rS2C_TASK_LIST\x12\"\n\x05tasks\x18\x01 \x03(\x0b\x32\x13.msg_task.USER_TASK\x12\x10\n\x08\x61\x63tivity\x18\x02 \x01(\x05\x12\x1b\n\x13\x61\x63tivity_reward_get\x18\x03 \x03(\x05\x12\x0c\n\x04type\x18\x04 \x01(\x05\"D\n\x13\x43\x32S_TASK_GET_REWARD\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0e\n\x06source\x18\x03 \x01(\x05\"\xb4\x01\n\x13S2C_TASK_GET_REWARD\x12&\n\tnext_task\x18\x01 \x01(\x0b\x32\x13.msg_task.USER_TASK\x12\x0f\n\x07task_id\x18\x02 \x03(\x05\x12\x10\n\x08\x61\x63tivity\x18\x03 \x01(\x05\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x0e\n\x06source\x18\x05 \x01(\x05\x12&\n\x05items\x18\x06 \x03(\x0b\x32\x17.msg_common.common_item\x12\x0c\n\x04\x63ode\x18\x07 \x01(\x05\";\n\x1c\x43\x32S_TASK_ACTIVITY_GET_REWARD\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\"I\n\x1cS2C_TASK_ACTIVITY_GET_REWARD\x12\x1b\n\x13\x61\x63tivity_reward_get\x18\x01 \x03(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x42\x0cZ\n./../../pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n./../../pb'
  _globals['_USER_TASK']._serialized_start=46
  _globals['_USER_TASK']._serialized_end=139
  _globals['_S2C_SYNC_TASK_INFO']._serialized_start=141
  _globals['_S2C_SYNC_TASK_INFO']._serialized_end=215
  _globals['_C2S_TASK_LIST']._serialized_start=217
  _globals['_C2S_TASK_LIST']._serialized_end=246
  _globals['_S2C_TASK_LIST']._serialized_start=248
  _globals['_S2C_TASK_LIST']._serialized_end=360
  _globals['_C2S_TASK_GET_REWARD']._serialized_start=362
  _globals['_C2S_TASK_GET_REWARD']._serialized_end=430
  _globals['_S2C_TASK_GET_REWARD']._serialized_start=433
  _globals['_S2C_TASK_GET_REWARD']._serialized_end=613
  _globals['_C2S_TASK_ACTIVITY_GET_REWARD']._serialized_start=615
  _globals['_C2S_TASK_ACTIVITY_GET_REWARD']._serialized_end=674
  _globals['_S2C_TASK_ACTIVITY_GET_REWARD']._serialized_start=676
  _globals['_S2C_TASK_ACTIVITY_GET_REWARD']._serialized_end=749
# @@protoc_insertion_point(module_scope)
