# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msg_login.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'msg_login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmsg_login.proto\x12\tmsg_login\"`\n\x08\x43\x32S_AUTH\x12\x0c\n\x04\x63uid\x18\x01 \x01(\t\x12\x0b\n\x03rid\x18\x02 \x01(\x05\x12\n\n\x02ts\x18\x03 \x01(\x03\x12\r\n\x05token\x18\x04 \x01(\t\x12\x0c\n\x04lang\x18\x05 \x01(\t\x12\x10\n\x08\x63urrency\x18\x06 \x01(\t\"e\n\x08S2C_AUTH\x12\x11\n\tserver_ts\x18\x01 \x01(\x03\x12\x11\n\ttime_zone\x18\x02 \x01(\x05\x12\x12\n\nis_created\x18\x04 \x01(\x08\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\x11\n\tis_newbie\x18\x07 \x01(\x08\")\n\rC2S_INIT_ROLE\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x0f\n\rS2C_INIT_ROLE\"\x0f\n\rC2S_HEARTBEAT\"5\n\rS2C_HEARTBEAT\x12\x11\n\tserver_ts\x18\x01 \x01(\x03\x12\x11\n\ttime_zone\x18\x02 \x01(\x05\"\x11\n\x0f\x43\x32S_BAN_ACCOUNT\"&\n\x0fS2C_BAN_ACCOUNT\x12\x13\n\x0b\x65xpire_time\x18\x01 \x01(\x03\"\x12\n\x10S2C_MULTI_DEVICE\"\x17\n\x15\x43\x32S_ENTER_GAME_FINISH\"\x17\n\x15S2C_ENTER_GAME_FINISHb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_C2S_AUTH']._serialized_start=30
  _globals['_C2S_AUTH']._serialized_end=126
  _globals['_S2C_AUTH']._serialized_start=128
  _globals['_S2C_AUTH']._serialized_end=229
  _globals['_C2S_INIT_ROLE']._serialized_start=231
  _globals['_C2S_INIT_ROLE']._serialized_end=272
  _globals['_S2C_INIT_ROLE']._serialized_start=274
  _globals['_S2C_INIT_ROLE']._serialized_end=289
  _globals['_C2S_HEARTBEAT']._serialized_start=291
  _globals['_C2S_HEARTBEAT']._serialized_end=306
  _globals['_S2C_HEARTBEAT']._serialized_start=308
  _globals['_S2C_HEARTBEAT']._serialized_end=361
  _globals['_C2S_BAN_ACCOUNT']._serialized_start=363
  _globals['_C2S_BAN_ACCOUNT']._serialized_end=380
  _globals['_S2C_BAN_ACCOUNT']._serialized_start=382
  _globals['_S2C_BAN_ACCOUNT']._serialized_end=420
  _globals['_S2C_MULTI_DEVICE']._serialized_start=422
  _globals['_S2C_MULTI_DEVICE']._serialized_end=440
  _globals['_C2S_ENTER_GAME_FINISH']._serialized_start=442
  _globals['_C2S_ENTER_GAME_FINISH']._serialized_end=465
  _globals['_S2C_ENTER_GAME_FINISH']._serialized_start=467
  _globals['_S2C_ENTER_GAME_FINISH']._serialized_end=490
# @@protoc_insertion_point(module_scope)
